### ISSUE TITLE
怎样平滑关闭SpringJupiterClient

### ISSUE THREAD

**Issue by hank-whu** [fengjiachun/Jupiter#43]
@fengjiachun 
如题，使用spring的情况下如何关闭Client、Server？

**Comment by fengjiachun** [comment]
需要主动关闭? 那么JupiterSpringClient/JupiterSpringServer有getClient()/getServer()方法, 从spring 容器拿到这两个bean, 再获取到client/server实例调用shutdownGracefully()即可

JupiterSpringClient/JupiterSpringServer都添加了shutdownHook来关闭 client/server
如果不是需要主动关闭client/server的话一般应该不用考虑这个问题, 不知道你是什么场景提出的这个问题? :)

**Comment by hank-whu** [comment]
我在做jmh压力测试，每一轮测试后都得主动关闭掉。
context.getBean(JupiterSpringClient.class).getClient().shutdownGracefully();
貌似不行的，还是有很多线程没被关掉。

**Comment by hank-whu** [comment]
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 25 seconds more...>

Non-finished threads:

Thread[DestroyJavaVM,5,main]

Thread[local.register.watch.executor #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at org.jupiter.registry.AbstractRegistryService$2.run(AbstractRegistryService.java:104)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[jupiter.connector-3-1,10,main]
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:745)

Thread[register.executor #0,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at org.jupiter.registry.AbstractRegistryService$1.run(AbstractRegistryService.java:76)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 19 seconds more...>

Non-finished threads:

Thread[DestroyJavaVM,5,main]

Thread[local.register.watch.executor #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at org.jupiter.registry.AbstractRegistryService$2.run(AbstractRegistryService.java:104)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[jupiter.connector-3-1,10,main]
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:745)

Thread[register.executor #0,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at org.jupiter.registry.AbstractRegistryService$1.run(AbstractRegistryService.java:76)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 14 seconds more...>

Non-finished threads:

Thread[DestroyJavaVM,5,main]

Thread[local.register.watch.executor #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at org.jupiter.registry.AbstractRegistryService$2.run(AbstractRegistryService.java:104)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[connector.timer #0,5,main]
  at java.lang.Thread.sleep(Native Method)
  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
  at java.lang.Thread.run(Thread.java:745)

Thread[jupiter.connector-3-1,10,main]
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:745)

Thread[register.executor #0,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at org.jupiter.registry.AbstractRegistryService$1.run(AbstractRegistryService.java:76)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

**Comment by fengjiachun** [comment]
@hank-whu 可否更新jupiter代码再试一下?

**Comment by hank-whu** [comment]
@fengjiachun 还有一个漏网之鱼

<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 25 seconds more...>

Non-finished threads:

Thread[register.executor #0,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at org.jupiter.registry.AbstractRegistryService$1.run(AbstractRegistryService.java:76)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

Thread[DestroyJavaVM,5,main]

**Comment by fengjiachun** [comment]
@hank-whu 这回应该可以了 :)

**Comment by hank-whu** [comment]
@fengjiachun 这次好了，发个新版本到mvn上吧

**Comment by fengjiachun** [comment]
@hank-whu 已发布新版本, mvn仓库会有些延时
https://oss.sonatype.org/#nexus-search;quick~org.jupiter-rpc

**Comment by fengjiachun** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jupiter-rpc%22%20AND%20jupiter

@hank-whu maven仓库中已经可以下载最新版本了

**Comment by hank-whu** [comment]
@fengjiachun 好的，多谢了

**Comment by fengjiachun** [comment]
@hank-whu 你的压测结果最终会发出文章吗? 到时可否分享一下?

**Comment by hank-whu** [comment]
@fengjiachun 会分享出来的，到时候通知你
