### ISSUE TITLE
java.lang.NoClassDefFoundError: io/opentracing/Tracer

### ISSUE THREAD

**Issue by uvletter** [fengjiachun/Jupiter#52]
maven配置
<dependency>
            <groupId>org.jupiter-rpc</groupId>
            <artifactId>jupiter-all</artifactId>
            <version>1.2.16</version>
</dependency>

当我运行README里面的HelloJupiterClient demo时，会抛标题上的错误，栈信息
Exception in thread "main" java.lang.NoClassDefFoundError: io/opentracing/Tracer
	at org.jupiter.tracing.TracerFactory.<clinit>(TracerFactory.java:38)
	at org.jupiter.tracing.OpenTracingContext.<clinit>(OpenTracingContext.java:33)
	at org.jupiter.tracing.OpenTracingFilter.doFilter(OpenTracingFilter.java:59)
	at org.jupiter.rpc.DefaultFilterChain.doFilter(DefaultFilterChain.java:34)
	at org.jupiter.rpc.consumer.invoker.AbstractInvoker$Chains.invoke(AbstractInvoker.java:146)
	at org.jupiter.rpc.consumer.invoker.AbstractInvoker.doInvoke(AbstractInvoker.java:43)
	at org.jupiter.rpc.consumer.invoker.SyncInvoker.invoke(SyncInvoker.java:52)
	at com.luv.ServiceTest$ByteBuddy$0TeSwTu2.sayHelloString(Unknown Source)
	at com.luv.HelloJupiterClient.main(HelloJupiterClient.java:31)
Caused by: java.lang.ClassNotFoundException: io.opentracing.Tracer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

是不是jupiter-all的maven打包有问题？我还试了前面若干个版本，发现这个问题一直存在，但是好奇为什么一直没人提这个issue，难道只是我自己环境的问题？

最近刚开始学习RPC框架，在研究Jupiter源码，如果问得有什么不对还请不要介意...

**Comment by fengjiachun** [comment]
@uvletter 抱歉给你造成困扰, jupiter-all忘了引入opentracing, 你可以在自己的pom引入一下, 下一个版本会修复这个问题

>            
            <dependency>
                <groupId>io.opentracing</groupId>
                <artifactId>opentracing-api</artifactId>
                <version>0.31.0</version>
            </dependency>
            <dependency>
                <groupId>io.opentracing</groupId>
                <artifactId>opentracing-noop</artifactId>
                <version>0.31.0</version>
            </dependency>

**Comment by fengjiachun** [comment]
@uvletter done

**Comment by KamleshSilag** [comment]
Thanks!
