### ISSUE TITLE
不支持java10？

### ISSUE THREAD

**Issue by hank-whu** [fengjiachun/Jupiter#59]
Linux java 10 上跑不起来

**Comment by fengjiachun** [comment]
在我的Mac上可以跑起来啊

**Comment by hank-whu** [comment]
嗯，那可能是你上次修改带来的问题
mvn clean package
java -jar jupiter-server-round-2-jar-with-dependencies.jar
抛出异常：
java.util.ServiceConfigurationError: org.jupiter.rpc.provider.processor.ProviderExecutorFactory: provider callerRuns could not be found
        at org.jupiter.common.util.JServiceLoader.fail(JServiceLoader.java:130)
        at org.jupiter.common.util.JServiceLoader.find(JServiceLoader.java:111)
        at org.jupiter.rpc.provider.processor.ProviderExecutors.<clinit>(ProviderExecutors.java:42)
        at org.jupiter.rpc.provider.processor.DefaultProviderProcessor.<init>(DefaultProviderProcessor.java:42)
        at org.jupiter.rpc.DefaultServer.withAcceptor(DefaultServer.java:91)
        at benchmark.rpc.Server.main(Server.java:24)

**Comment by hank-whu** [comment]
版本：1.2.19.Beta2

**Comment by fengjiachun** [comment]
你github代码和本地是同步的么?
你本地有这个文件? https://github.com/hank-whu/rpc-benchmark/blob/master/jupiter-server/src/main/resources/META-INF/services/org.jupiter.rpc.provider.processor.ProviderExecutorFactory

我下载了你的最新代码 貌似没问题

**Comment by hank-whu** [comment]
知道了，是 assembly 打包的问题，我自己解决下吧
