### ISSUE TITLE
TCP_FASTOPEN_CONNECT报错

### ISSUE THREAD

**Issue by hank-whu** [fengjiachun/Jupiter#68]
Failed to set channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN_CONNECT' with value 'false' for channel
-----------------------
升级到最新版后报这个错

**Comment by hank-whu** [comment]
```java
io.netty.channel.ChannelException: setsockopt() failed: Protocol not available
        at io.netty.channel.epoll.LinuxSocket.setTcpFastOpenConnect(Native Method)
        at io.netty.channel.epoll.LinuxSocket.setTcpFastOpenConnect(LinuxSocket.java:71)
        at io.netty.channel.epoll.EpollSocketChannelConfig.setTcpFastOpenConnect(EpollSocketChannelConfig.java:534)
        at io.netty.channel.epoll.EpollSocketChannelConfig.setOption(EpollSocketChannelConfig.java:166)
        at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:457)
        at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:442)
        at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:269)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at org.jupiter.transport.netty.JNettyTcpConnector.connect(JNettyTcpConnector.java:172)
        at org.jupiter.transport.netty.JNettyTcpConnector.connect(JNettyTcpConnector.java:99)
        at org.jupiter.transport.netty.NettyTcpConnector.connect(NettyTcpConnector.java:130)
        at org.jupiter.transport.netty.NettyTcpConnector.connect(NettyTcpConnector.java:41)
        at benchmark.rpc.Client.<init>(Client.java:62)
        at benchmark.rpc.generated.Client_jmhType_B1.<init>(Client_jmhType_B1.java:3)
        at benchmark.rpc.generated.Client_jmhType_B2.<init>(Client_jmhType_B2.java:3)
        at benchmark.rpc.generated.Client_jmhType_B3.<init>(Client_jmhType_B3.java:2)
        at benchmark.rpc.generated.Client_jmhType.<init>(Client_jmhType.java:2)
        at benchmark.rpc.generated.Client_listUser_jmhTest._jmh_tryInit_f_client0_G(Client_listUser_jmhTest.java:437)
        at benchmark.rpc.generated.Client_listUser_jmhTest.listUser_AverageTime(Client_listUser_jmhTest.java:162)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by fengjiachun** [comment]
加了一个linux 4.11版本才支持的选项导致报错, 我现在改一下

**Comment by fengjiachun** [comment]
@hank-whu v1.2.24已发布到maven仓库

**Comment by hank-whu** [comment]
好的
