### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/curator/framework/api/BackgroundCallback异常

### ISSUE THREAD

**Issue by rabee198** [fengjiachun/Jupiter#81]
只引入一个依赖

 < dependencies>
		< dependency>
			< groupId>org.jupiter-rpc</groupId>
			< artifactId>jupiter-all</artifactId>
			< version>1.2.26</version>
		< /dependency>
  < /dependencies>	
但是会报这样的异常：
Exception in thread "main" java.util.ServiceConfigurationError: org.jupiter.registry.RegistryService: provider org.jupiter.registry.zookeeper.ZookeeperRegistryService could not be instantiated
	at org.jupiter.common.util.JServiceLoader.fail(JServiceLoader.java:130)
	at org.jupiter.common.util.JServiceLoader.find(JServiceLoader.java:111)
	at org.jupiter.rpc.DefaultClient.<init>(DefaultClient.java:72)
	at org.jupiter.rpc.DefaultClient.<init>(DefaultClient.java:62)
	at JupiterClient.main(JupiterClient.java:38)
Caused by: java.lang.NoClassDefFoundError: org/apache/curator/framework/api/BackgroundCallback
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.jupiter.common.util.JServiceLoader.find(JServiceLoader.java:107)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.apache.curator.framework.api.BackgroundCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by fengjiachun** [comment]
是不是 curator jar 包冲突了
